# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
a = s.split()
print(a)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
txt = "The diameter of {planet} is {diameter} kilometers."
a=txt.format(planet="Earth",diameter=12742)
print(a)

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d= {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d= {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'] [3] ['tricky'] [3] ['target'] [3])




hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
import numpy as np
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
array=np.arange(20,35,2)
print(array)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
import pandas as pd
data={'Name':['aakash','jeeva','jai'],'Age':[20,19,21]}
df=pd.DataFrame(data)
df

Name  Age
0  aakash   20
1   jeeva   19
2     jai   21

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import pandas as pd
p= pd.date_range(start='1-1-2023',end='10-2-2023',freq='12H')
for val in p:
  print(val)

2023-01-01 00:00:00
2023-01-01 12:00:00
2023-01-02 00:00:00
2023-01-02 12:00:00
2023-01-03 00:00:00
2023-01-03 12:00:00
2023-01-04 00:00:00
2023-01-04 12:00:00
2023-01-05 00:00:00
2023-01-05 12:00:00
2023-01-06 00:00:00
2023-01-06 12:00:00
2023-01-07 00:00:00
2023-01-07 12:00:00
2023-01-08 00:00:00
2023-01-08 12:00:00
2023-01-09 00:00:00
2023-01-09 12:00:00
2023-01-10 00:00:00
2023-01-10 12:00:00
2023-01-11 00:00:00
2023-01-11 12:00:00
2023-01-12 00:00:00
2023-01-12 12:00:00
2023-01-13 00:00:00
2023-01-13 12:00:00
2023-01-14 00:00:00
2023-01-14 12:00:00
2023-01-15 00:00:00
2023-01-15 12:00:00
2023-01-16 00:00:00
2023-01-16 12:00:00
2023-01-17 00:00:00
2023-01-17 12:00:00
2023-01-18 00:00:00
2023-01-18 12:00:00
2023-01-19 00:00:00
2023-01-19 12:00:00
2023-01-20 00:00:00
2023-01-20 12:00:00
2023-01-21 00:00:00
2023-01-21 12:00:00
2023-01-22 00:00:00
2023-01-22 12:00:00
2023-01-23 00:00:00
2023-01-23 12:00:00
2023-01-24 00:00:00
2023-01-24 12:00:00
2023-01-25 00:00:00
2023-01-25 12:00:00


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
import pandas as pd
lists=[[1, 'aaa' ,22], [2 , 'bbb' ,25], [3, 'ccc' ,24]]
df=pd.DataFrame(lists,columns=['number','Name','Age' ])
print(df)

   number Name  Age
0       1  aaa   22
1       2  bbb   25
2       3  ccc   24
